<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>asp</string>
    <key>scopeName</key>
    <string>source.asp</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.asp</string>
            <key>begin</key>
            <string>%\*</string>
            <key>end</key>
            <string>\*%</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.asp</string>
            <key>match</key>
            <string>%.*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.asp</string>
            <key>match</key>
            <string>\bnot\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.asp</string>
            <key>match</key>
            <string>:-</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.and.asp</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.or.asp</string>
            <key>match</key>
            <string>;</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.constant.cut.asp</string>
            <key>match</key>
            <string>!=</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.constant.cut.asp</string>
            <key>match</key>
            <string>>></string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.asp</string>
            <key>match</key>
            <string>#(count|max|min|sum)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.asp</string>
            <key>comment</key>
            <string>asprilo types and statements</string>
            <key>match</key>
            <string>(node|highway|robot|shelf|pickleStation|product|order|carries)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.asp</string>
            <key>comment</key>
            <string>asprin types and statements</string>
            <key>match</key>
            <string>(less\s*\(\s*cardinality\s*\)|more\s*\(\s*cardinality\s*\)|less\s*\(\s*weight\s*\)|more\s*\(\s*weight\s*\)|preference|pareto|subset|superset|minmax|maxmin|aso|poset|cp|#(preference|optimize))\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.function.asp</string>
            <key>comment</key>
            <string>Other language (Python, Lua) function call</string>
            <key>match</key>
            <string>@[a-z][A-Za-z0-9_]*\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.function.asp</string>
            <key>comment</key>
            <string>Gringo functions</string>
            <key>match</key>
            <string>#(maximize|minimize|show|hide|heuristic|showsig|sup|inf|true|false|forget|external|cumulative|disjoint|const|base)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.function.asp</string>
            <key>comment</key>
            <string>Include</string>
            <key>match</key>
            <string>#include\s([<](incmode|csp)[>][.])?</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.function.asp</string>
            <key>comment</key>
            <string>Program</string>
            <key>match</key>
            <string>#program\s((base|step\(\w\)*|check\(\s*\w\s*\)*)[.])?</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>Gringo script python</string>
            <key>begin</key>
            <string>#script\s*\(\s*python\s*\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.function.asp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>#end[.]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.function.asp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.python</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>Gringo script lua</string>
            <key>begin</key>
            <string>#script\s*\(\s*lua\s*\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.function.asp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>#end[.]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.function.asp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.lua</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.tag.asp</string>
            <key>match</key>
            <string>[a-z][A-Za-z0-9_]*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.asp</string>
            <key>match</key>
            <string>\b[A-Z][A-Za-z0-9_]*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>string.asp</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.asp</string>
            <key>match</key>
            <string>0|[1-9][0-9]*</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>